name: Prepare release

on:
  push:
    branches:
      - main
    paths-ignore:
      - VERSION

jobs:
  candidate:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Preparing the next main release
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          develop-branch: main
          version-files: package.json
